
### create

POST {{host}}/answers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "fuck answer",
  "question": {
    "id": "3ca7344c-de9a-4d7f-86b8-16b7a825f3bb"
  }
}

### update
PUT {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "updated answer"
}

### get one
GET {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be

### delete
DELETE {{host}}/answers/dad26e6a-3ef0-47c9-83ac-b99301ab2457
Authorization: Bearer {{token}}

### star
POST {{host}}/answers/32d8ffd3-2192-47f4-bec5-9a065e13b99a/star
Authorization: Bearer {{token}}

### unStar
POST {{host}}/answers/32d8ffd3-2192-47f4-bec5-9a065e13b99a/unStar
Authorization: Bearer {{token}}

### toggleStar
POST {{host}}/answers/95696bba-474a
Authorization: Bearer {{token}}

### starCount
GET {{host}}/answers/32d8ffd3-2192-47f4-bec5-9a065e13b99a/starCount

### isStarByRequestUser
GET {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be/isStarByRequestUser
Authorization: Bearer {{token}}

### canUpdate
GET {{host}}/answers/0d39c8ce-b3f9-4b6a-8fe9-b7f728674937/canUpdate
Authorization: Bearer {{token}}

