
### create

POST {{host}}/answers
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "fuck answer",
  "question": {
    "id": "45aa5435-93c2-4469-ac9c-a8000fa184f8"
  }
}

### update
PUT {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "text": "updated answer"
}

### get one
GET {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be

### delete
DELETE {{host}}/answers/dad26e6a-3ef0-47c9-83ac-b99301ab2457
Authorization: Bearer {{token}}

### star
POST {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be/star
Authorization: Bearer {{token}}

### unStar
POST {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be/unStar
Authorization: Bearer {{token}}

### unStar
POST {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be/toggleStar
Authorization: Bearer {{token}}

### unStar
GET {{host}}/answers/95696bba-474a-4d38-b16b-1236950dc2be/isStarByRequestUser
Authorization: Bearer {{token}}

