### create
POST {{host}}/questions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "fuck title",
  "description": "fuck description",
  "tags": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

### update
PUT {{host}}/questions/29
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "test2",
  "description": "test2 description2",
  "tags": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

### get by id
GET {{host}}/questions/3

### get list
GET {{host}}/questions?per=3&current=1&search={"username": "buuug7"}

### delete
DELETE {{host}}/questions/28

### get question tags
GET {{host}}/questions/3/tags

### get question answers
GET {{host}}/questions/2/answers?per=2


