### create
POST {{host}}/questions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "wind force",
  "description": "DIABLO wind force",
  "tags": []
}

### update
PUT {{host}}/questions/45aa5435-93c2-4469-ac9c-a8000fa184f8
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "test2",
  "description": "test2 description2",
  "tags": [
    {
      "id": "56b24c25-e90c-4925-9068-09382f67f8b4"
    }
  ]
}

### get by id
GET {{host}}/questions/59513087-402b-49ad-aa6d-b546f505d5b5

### get list
GET {{host}}/questions?perPage=3&currentPage=2&search={"username": "buuug7"}

### delete
DELETE {{host}}/questions/d0a75cfa-0484-4d9f-8088-78352ae6aa63
Authorization: Bearer {{token}}

### get question tags
GET {{host}}/questions/59513087-402b-49ad-aa6d-b546f505d5b5/tags

### get question answers
GET {{host}}/questions/e873c799-2e45-4ce8-bf65-ce38f0e1c90b/answers?perPage=10


