### create
POST {{host}}/questions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "are every read force",
  "description": "Diablo",
  "tags": [
    {
      "id": "8da939d7-670f-4b2f-ad38-62675b396bcb"
    },
    {
      "id": "97468664-dacf-4bfe-ad74-8a4658f295d8"
    }
  ]
}

### update
PUT {{host}}/questions/2e51af7b-dd0f-4db4-8eff-203b81b8acce
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "test2",
  "description": "test2 description2",
  "tags": [
    {
      "id": "56b24c25-e90c-4925-9068-09382f67f8b4"
    }
  ]
}

### get by id
GET {{host}}/questions/57a6f84a-0194-40fe-8539-7cc754b333a7

### get list
GET {{host}}/questions?perPage=3&currentPage=2

### get the most answers questions
GET {{host}}/questions/analysis/getByMostAnswers?limit=5

### delete
DELETE {{host}}/questions/2e51af7b-dd0f-4db4-8eff-203b81b8acce
Authorization: Bearer {{token}}

### get question tags
GET {{host}}/questions/59513087-402b-49ad-aa6d-b546f505d5b5/tags

### get question answers
GET {{host}}/questions/69ad24a8-eec5-4189-b3ff-61b7a11978f5/answers?perPage=10
