### get user by email
GET {{host}}/users/profile/youpp@126.com
Authorization: Bearer {{token}}

### create
POST {{host}}/users
Content-Type: application/json

{
  "name": "buuug7",
  "email": "youpp@126.com",
  "password": "123456",
  "loginFrom": {}
}
